In [17]:
## Written by Mohammad Hadi

import numpy as np
A = np.array([[2.,3.,2.,2., -1.,-1.,-3.,-5., 3.,5.,5.,3.]])
A = A.reshape((3,4))

rows, cols = A.shape
for c in range(cols-1):    
    for i in range(rows):
        t = 0 # initial value
        is_diagonal = False;
        is_off_diagonal = False;
        temp_not_pivot = 0.
        for j in range(cols):

            if i == 0 and c == j: # diagonal element
                t = A[i,j]
                is_diagonal = True;

            if is_diagonal == True: # make pivot 
                A[i,j] = A[i,j]/t        
                
            if i > 0 and c == j: # select non pivot index
                temp_not_pivot = -A[i,j]
                is_off_diagonal = True
            
            if is_off_diagonal == True:
                A[i,j] = ((temp_not_pivot*(A[0,j]))+A[i,j])
        
        is_diagonal = False
        is_off_diagonal = False
            
    #interchange first row with the current row +1
    if c < rows -1: # swapping is with next current row, c+1 not exceeds from Matrix rows index 
        A[[0, c+1]] = A[[c+1, 0]]


print("Not in diagonal form \n", A, "\n") # the matrix is not in the diagonal form

for i in range(rows):
    for j in range(cols-1): # not calculate x vector from the matrix
        if A[i,j] > 0: # found the pivot
            A[[i,j]] = A[[j,i]]
print("Diagonal form \n",A)
    
    
        

Not in diagonal form 
 [[ 0.  0.  1.  1.]
 [ 1.  0.  0.  6.]
 [ 0.  1.  0. -4.]] 

Diagonal form 
 [[ 1.  0.  0.  6.]
 [ 0.  1.  0. -4.]
 [ 0.  0.  1.  1.]]


In [18]:
print("fsdf")


fsdf


In [39]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    print(left)
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))


[3, 6, 8, 1, 2, 1]
[]
[3, 6, 2]
[3, 2]
[]
[1, 1, 2, 3, 6, 8, 10]


In [38]:
my_list = [1,3,2,4,6,1]
left = [t for t in my_list if t == 6]
print(left)

[6]
