# 03: Solution

### Notebook accompanying  the [Scientific Computing Lecture HS 2019](https://dmi.unibas.ch/de/studium/computer-science-informatik/lehrangebot-hs18/main-lecture-scientific-computing/)
#### Tutorial by [Sebastian Mathias Keller](http://bmda.cs.unibas.ch/)
#### University of Basel [Institute for Mathematics and Computer Science](http://informatik.unibas.ch/)

## 3.1 LU Decomposition

In [1]:
# LU decomposition by applying elementary R-matrices

import numpy as np

A = np.array([[1,0,-5], [-6,2,9], [2,-3,2]])

print("A:\n", A)

rows, cols = A.shape

# init L as identity matrix and U as null matrix
L = np.identity(rows)
U = np.copy(A)

for i in range(rows):
    for j in range(i+1,rows):        
        
        print(i,j)
        
        # calculate multiplier m for transformation matrix R
        m = -A[j,i] / A[i,i]
        
        # construct R
        R = np.identity(rows)
        R[j, i] = m
        
        # and its inverse
        invR = np.identity(rows)
        invR[j, i] = -m
        
        # apply R to A (this is the standard Gauss-Jordan step)
        A = np.dot(R, A)

        # apply R (or its inverse) to L and U
        L = np.dot(L, invR)
        U = np.dot(R, U)


# this is the final L
print("\nL\n",L)

# this is the final U
print("\nU\n",U)

# make check:
print("L*U\n")
print(np.dot(L,U))

A:
 [[ 1  0 -5]
 [-6  2  9]
 [ 2 -3  2]]
0 1
0 2
1 2

L
 [[ 1.   0.   0. ]
 [-6.   1.   0. ]
 [ 2.  -1.5  1. ]]

U
 [[  1.    0.   -5. ]
 [  0.    2.  -21. ]
 [  0.    0.  -19.5]]
L*U

[[ 1.  0. -5.]
 [-6.  2.  9.]
 [ 2. -3.  2.]]


##  3.2 Back- and Forward Substitution: LU Decomposition for solving Ax = b

In [2]:
import numpy as np

A = np.array([[1,0,-5, -6,2,9, 2,-3,2]])
A = A.reshape((3, 3))
print("A:\n")
print(A)


# Forward substitution: solve L*c = b

print("\nForward substitution:\n")

L = np.array([[1,0,0],  [-6,1,0],  [2,-1.5,1]]) # L is the result from ex. 3.1
b = np.array([-23,54,2])
n = L.shape[0]
print('n:', n)
print("L:\n")
print(L)
print("\nb:\n")
print(b)


c = np.zeros(n)
for i in range(0,n):
    for j in range(0,i):
        print("i",i,"j",j)
        b[i] = b[i] - L[i,j]*c[j]
    c[i] = b[i]/L[i,i]

print("\nintermediate solution vector c:\n")
print(c,"\n\n")

    
# Back substitution: solve U*x = c

print("Back substitution:\n")

U = np.array([[1,0,-5,  0,2,-21,  0,0,-19.5]]) # U is the result from ex. 3.1
U = U.reshape((3, 3))
n = U.shape[0]
print('n:', n)
print("U:\n")
print(U)
print("\nc:\n")
print(c)

x = np.zeros(n)
for i in range(n-1,-1,-1):
    for j in range(i+1,n):
        c[i] = c[i] - U[i,j]*x[j]
    x[i] = c[i]/U[i,i]

print("\nfinal solution vector x:\n")
print(x)
print("------------------------------")


print("\ncheck: A*x = ??[-23, 54, 2]??\n")
print("\n",np.dot(A, x))
print("------------------------------")

A:

[[ 1  0 -5]
 [-6  2  9]
 [ 2 -3  2]]

Forward substitution:

n: 3
L:

[[ 1.   0.   0. ]
 [-6.   1.   0. ]
 [ 2.  -1.5  1. ]]

b:

[-23  54   2]
i 1 j 0
i 2 j 0
i 2 j 1

intermediate solution vector c:

[-23. -84. -78.] 


Back substitution:

n: 3
U:

[[  1.    0.   -5. ]
 [  0.    2.  -21. ]
 [  0.    0.  -19.5]]

c:

[-23. -84. -78.]

final solution vector x:

[-3.  0.  4.]
------------------------------

check: A*x = ??[-23, 54, 2]??


 [-23.  54.   2.]
------------------------------


## 3.3 Cholesky Decomposition

In [3]:
# Cholesky Decomposition

import numpy as np

A = np.array([[4,12,-16, 12,37,-43, -16,-43,98]])


L_solution = np.array([[2,0,0, 6,1,0, -8,5,3]])

A = A.reshape((3, 3))
print("A:\n")
print(A)

n,m  = A.shape

if( n!=m ):
    print("Error: A must be square")
    
L = np.zeros((n,n))

for i in range(n):
    for j in range(i+1):
        
        if( i==0 and j==0 ):
            L[0,0] = np.sqrt( A[0,0] )
        
        else:
            
            if( i==j ):
                s = 0
                for k in range(i):
                    s = s + L[i,k]*L[i,k]
                L[i,i] = np.sqrt( A[i,i] - s )
                
            if ( j<i ):
                s = 0
                for k in range(j):
                    s = s + L[i,k] * L[j,k]
                L[i,j] = 1/L[j,j] * ( A[i,j] - s )

print("\n",L)
print("\n",np.transpose(L))
print("\n",np.dot(L, np.transpose(L)))


print("\nSOLUTION:\n", L_solution.reshape((3,3)))

print("\ncheck: L*Lt = ?\n")
print("\n",np.dot(L, np.transpose(L)))
print("------------------------------")

A:

[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]

 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

 [[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]

 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

SOLUTION:
 [[ 2  0  0]
 [ 6  1  0]
 [-8  5  3]]

check: L*Lt = ?


 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
------------------------------
