In [229]:
#LU_decomposition
import numpy as np

A = np.array([[1.,0.,-5.], [-6.,2.,9.], [2.,-3.,2.]])
b = np.array([[-23,54,2]])
b = b.T
rows, cols = A.shape

for i in range(rows):
    for j in range(rows):
        if j > i:
            l_elm = A[j,i]/A[i,i]
            A[j,i:] = A[j,i:] - l_elm * A[i,i:]
            A[j,i] = l_elm
            
print("matrix A consist of L and U \n", A, "\n")

#finding LC = b, finding C?
c = np.zeros((rows,1))

for i in range(rows):
    L_sum_value = 0.
    for j in range(rows):
        #sum multiplication of all corresponding A elements with b elements 
        if j < i:
            L_sum_value = L_sum_value + A[i,j]*c[j]
            
    if i == 0:
        c[i] = b[i]
    else:
        c[i] = b[i] - L_sum_value

#finding UX = c, finding x?
x = np.zeros((rows,1))

for i in range(rows-1, -1, -1):
    U_sum_value = 0.
    for j in range(rows-1, -1, -1):
        if j > i:
            U_sum_value = U_sum_value + A[i,j]*x[j]
            
    # first row for backward substitution                                   
    if i == rows-1: 
        x[i] = c[i]/A[i,i]
    else:
         x[i] = (c[i] - U_sum_value)/A[i,i] 
            
print("c solution: \n", c, "\n")                                         
print("x solution: \n", x, "\n")                                         
                                

matrix A consist of L and U 
 [[  1.    0.   -5. ]
 [ -6.    2.  -21. ]
 [  2.   -1.5 -19.5]] 

c solution: 
 [[-23.]
 [-84.]
 [-78.]] 

x solution: 
 [[-3.]
 [ 0.]
 [ 4.]] 

