### Structure of SVD by Sebastian

In [ ]:
import numpy as np 
from numpy.linalg import* 

A = np.array([[1,0],[2,1],[0,1]])

print(A)
U,S_, Vt = np.linalg.svd(A, full_matrices= True)

print("U:\n", U, "\n")
S =np.zeros([3,2])
S[0,0] = S_[0]
S[1,1] = S_[1]
print("S:\n", S, "\n")
print("V:\n", Vt.T, "\n")

#If we set the last column of U to zero, nothing would change, 
#because the last row of S is zero
U[:,-1] = 0
print("U reduced:\n", U)
    
matrix = U.dot(S).dot(Vt)
print("CHECK USVt:\n", matrix.round()

In [40]:
#max singular value/ min of singualar value = kondition number
#what is residual? 
#the error, Ax -b= residual

#small kondition => cause better dedomposition of svd


In [4]:
import numpy as np 
from numpy.linalg import* 

A = np.array([[5,5],[-1,7]])

print(A)
U,S_, Vt = np.linalg.svd(A, full_matrices= True)

print("U:\n", U, "\n")
S =np.zeros([2,2])
S[0,0] = S_[0]
S[1,1] = S_[1]
print("S:\n", S, "\n")
print("V:\n", Vt.T, "\n")
 
print("U reduced:\n", U)
    
matrix = U.dot(S).dot(Vt)
print("CHECK USVt:\n", matrix.round())

[[ 5  5]
 [-1  7]]
U:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 

S:
 [[8.94427191 0.        ]
 [0.         4.47213595]] 

V:
 [[ 0.31622777  0.9486833 ]
 [ 0.9486833  -0.31622777]] 

U reduced:
 [[0.70710678 0.        ]
 [0.70710678 0.        ]]
CHECK USVt:
 [[2. 6.]
 [2. 6.]]
