In [ ]:
#If the matrix has less column than row (overdetermined), then the number of eingenvalues and eigenvectors
# are equal to number of columns.
#underdeterminded system number of eigenvalues are equal to number of rows. 

#In both cases we set max_R_C => (maximum number of rows or columns), each one of them are less, then
#will be assigned to max_R_C


In [19]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as spla
import math

# tall and skinny w/nullspace
A = np.array([[5,0], [-2,2], [3,-1]])
b = np.array([[3,2,-1]])
b = b.T 

print("A: \n", A)

max_R_C = 0
rows, cols = A.shape
if rows <= cols:
    max_R_C = rows;
else:
    max_R_C = cols;
    
U, sigma, VT = la.svd(A)

#Create Sigma if we multiply all svd decomposition, we must get back A
Sigma = np.zeros(A.shape)
Sigma[:max_R_C,:max_R_C] = np.diag(sigma)
print("A = U * Sigma * VT: \n", U.dot(Sigma.dot(VT)).round())

#Shape Sigma_pinv has the transpose shape of A, that we can multiply with Ut
Sigma_pinv = np.zeros(A.shape).reshape(A.shape[1],A.shape[0])
#Sigma_pinv is the pseudoinverse of sigma
Sigma_pinv[:max_R_C,:max_R_C] = np.diag(1/sigma[:max_R_C])

Sigma_pinv.round(max_R_C)

x_svd = VT.T.dot(Sigma_pinv).dot(U.T).dot(b)

print("-----------------")
print("Sigma_pinv = 1/sigma")
print("x_svd = V * 1/sigma * UT * b : \n")
print("x_svd: \n", x_svd)

A: 
 [[ 5  0]
 [-2  2]
 [ 3 -1]]
A = U * Sigma * VT: 
 [[ 5.  0.]
 [-2.  2.]
 [ 3. -1.]]
-----------------
Sigma_pinv = 1/sigma
x_svd = V * 1/sigma * UT * b : 

x_svd: 
 [[0.5319]
 [1.7447]]
