In [3]:
from numpy import *

A = zeros([4,4])
rows, shape = A.shape

b = zeros([4,1])

row_sum = 0
#Fill the 4*4 matrix  
for i in range(1,5):
    for j in range(1,5):
        A[i-1,j-1] = 1/(100*i + 0.01) + j;
        row_sum += A[i-1,j-1];
    b[i-1, 0] = row_sum;

#Compute SVD
U, sigma, Vt = linalg.svd(A);

print("A: \n", A,"\n");
print("b: \n", b, "\n");

#find the unknown of Ax = b
def getUnknownOfA(): 
    Sigma_pinv = zeros([4,4]);
    Sigma_pinv = diag(1/sigma)
    
    x = Vt.T.dot(Sigma_pinv.dot(U.T.dot(b)));
    return x;
    
x1 = getUnknownOfA();
print("X1: Ax = b\n", x1)

#set zero to the smallest singular value
sigma[1] = 0;

#move the zero singular value to last column and change the position of Vt
sigma[[3,1]] = sigma[[1,3]];
Vt[[3,1]] = Vt[[1,3]];

#Make sigma as diagonal
Sigma = zeros([4,1]);
Sigma = diag(sigma)

#B Matrix has smallest SV as zero
B = U.dot(Sigma.dot(Vt));
print("Matrix B has set the smallest singular value to zero");
print("Matrix B: \n", B, "\n");

#Compute the rank of A and B matrices
print("Rank A :", linalg.matrix_rank(A));
print("Rank B :", linalg.matrix_rank(B));

#find the unknown of Bx = b
def getUnknownOfB(): 
    Sigma_pinv = zeros([4,4]);
    Sigma_pinv[:3,:3] = diag(1/sigma[:3])
    
    x = Vt.T.dot(Sigma_pinv.dot(U.T.dot(b)));
    return x;
    
x2 = getUnknownOfB();
print("x2: Bx = b \n", x2)


A: 
 [[1.009999   2.009999   3.009999   4.009999  ]
 [1.00499975 2.00499975 3.00499975 4.00499975]
 [1.00333322 2.00333322 3.00333322 4.00333322]
 [1.00249994 2.00249994 3.00249994 4.00249994]] 

b: 
 [[10.039996  ]
 [20.059995  ]
 [30.07332789]
 [40.08332764]] 

X1: Ax = b
 [[-5.97727052e+16]
 [ 1.28704407e+17]
 [-7.80906981e+16]
 [ 9.15899643e+15]]
Matrix B has set the smallest singular value to zero
Matrix B: 
 [[1.00681295 2.0084068  3.01000066 4.01159451]
 [1.00514018 2.00506993 3.00499968 4.00492943]
 [1.00458255 2.00395756 3.00333257 4.00270758]
 [1.00430373 2.00340136 3.002499   4.00159663]] 

Rank A : 2
Rank B : 1
x2: Bx = b 
 [[ 2.74706256e+17]
 [-5.51155500e+17]
 [ 2.78192234e+17]
 [-1.74298898e+15]]
